### ISSUE TITLE
TileDB-VCF

### ISSUE THREAD

**Issue by leipzig** [NCBI-Codeathons/vcf-4-population-genomics-team-park#1]
Hi @dpark01 @npcarter @yxhan @dh-bioinfo @alexa-salsbury I really enjoyed reading this report. If you think it would useful I could add some info about [TileDB-VCF](https://github.com/TileDB-Inc/TileDB-VCF) into the mix here as a pull request. For some context, TileDB got its start from the GenomicsDB project you mention, and now we have over 50 developers expanding its capabilities and integrations.

**Comment by dpark01** [comment]
Hi @leipzig certainly feel free to!

In a way, this repo is kind of documenting a short lived (1 week) project and what limited things we were able to dig up in that period of time--I hadn't thought too hard of maintaining it as a living doc but feel free to PR and I'll snapshot a version of this repo prior to merging your PR that represents the end state of the codeathon.

**Comment by leipzig** [comment]
OK thanks for giving me this opportunity
https://github.com/NCBI-Codeathons/vcf-4-population-genomics-team-park/pull/2

Great work - I learned a couple things from this!

**Comment by dpark01** [comment]
Closed by #2
